### ISSUE TITLE
Import support

### ISSUE THREAD

**Issue by xinthose** [LinusU/inactivity-timer#2]
Hello,

Can we support Angular 2+ import please?  Like so: 

`import { createInactivityTimer } from "inactivity-timer";`  

I can use:

`import * as createInactivityTimer from "inactivity-timer";` 

but then calling ` this.lockTimer = createInactivityTimer(...)` yields this error:

> This expression is not callable.
>   Type '{ default: (threshold: string | number, onInactive: Function) => InactivityTimer; }' has no call signatures.ts(2349)
> node.service.ts(26, 1): Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.

**Comment by LinusU** [comment]
Unfortunately TypeScript doesn't support combining both CommonJS and Module exports from the same file, so I cannot do this without releasing a new major version.

That being said, you should be able to import it as you first stated if you set [`esModuleInterop: true` in your TypeScript config](https://www.typescriptlang.org/docs/handbook/compiler-options.html#compiler-options).

If you don't want to/can't change your TypeScript config, you should also be able to [import it as such](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require):

```typescript
import createInactivityTimer = require('inactivity-timer')
```
